# Generated by Django 4.0.2 on 2023-05-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientOnCall', '0003_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.IntegerField(default=-1),
        ),
    ]
