# Generated by Django 4.2.1 on 2023-05-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientOnCall', '0004_alter_patient_patientid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
