# Generated by Django 4.2.1 on 2023-06-01 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientoncall_api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('patientId', models.IntegerField(default=None, editable=False, primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
