# Generated by Django 4.2.1 on 2023-06-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0005_alter_patientuser_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='patientAddress',
            field=models.TextField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='patientBirthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
