# Generated by Django 4.2.1 on 2023-06-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientoncall_api', '0006_patientuser_patientaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug', models.TextField(max_length=256)),
                ('dosage', models.TextField(max_length=1024)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('duration', models.TextField(max_length=1024)),
                ('route', models.TextField(max_length=1024)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
