# Generated by Django 4.2.1 on 2023-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0007_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='admissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='consultant',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='dischargeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='visitType',
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='summary',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
