# Generated by Django 4.2.1 on 2023-06-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0010_alter_labhistory_report_alter_medicalhistory_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='current', max_length=32),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='consultant',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='visitType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patientuser',
            name='patientAddress',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='drug',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='route',
            field=models.CharField(max_length=1024),
        ),
    ]
