# Generated by Django 4.2.1 on 2023-06-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0010_alter_labhistory_report_alter_medicalhistory_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='letter',
        ),
    ]
