# Generated by Django 4.2.1 on 2023-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0011_remove_medicalhistory_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='letter',
            field=models.FileField(blank=True, null=True, upload_to='letterattachments/'),
        ),
    ]
