# Generated by Django 4.2.1 on 2023-06-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0012_medicalhistory_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='letter',
            field=models.FileField(blank=True, default=True, null=True, upload_to='letterattachments/'),
        ),
    ]
