# Generated by Django 4.2.1 on 2023-06-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0011_prescription_status_alter_medicalhistory_consultant_and_more'),
        ('patientoncall_api', '0013_alter_medicalhistory_letter'),
    ]

    operations = [
    ]
