# Generated by Django 4.2.1 on 2023-06-08 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0014_merge_20230607_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='admissionDate',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='consultant',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='dischargeDate',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='visitType',
            field=models.CharField(choices=[('GP Consultation', 'GPCONSULTATION'), ('Hospital Visit', 'HOSPITALVISIT')], default='Hospital Visit', max_length=20),
        ),
    ]
