# Generated by Django 4.2.1 on 2023-06-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0015_alter_medicalhistory_admissiondate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='addToMedicalHistory',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='visitType',
            field=models.CharField(choices=[('GP Consultation', 'GP Consultation'), ('Hospital Visit', 'Hospital Visit')], default='Hospital Visit', max_length=20),
        ),
    ]
