# Generated by Django 4.2.1 on 2023-06-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0016_alter_medicalhistory_consultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='comments',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
