# Generated by Django 4.2.1 on 2023-06-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0016_medicalhistory_addtomedicalhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='addToMedicalHistory',
            field=models.BooleanField(default=True),
        ),
    ]
