# Generated by Django 4.2.1 on 2023-06-08 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientoncall_api', '0017_prescription_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription',
            new_name='Medication',
        ),
    ]
