# Generated by Django 4.2.1 on 2023-06-09 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0017_alter_medicalhistory_addtomedicalhistory'),
        ('patientoncall_api', '0018_rename_prescription_medication'),
    ]

    operations = [
    ]
