# Generated by Django 4.2.1 on 2023-06-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0020_alter_medicalhistory_visittype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'ordering': ('-admissionDate',)},
        ),
    ]
