# Generated by Django 4.2.1 on 2023-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0024_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='byPatient',
            field=models.BooleanField(default=False),
        ),
    ]
