# Generated by Django 4.2.1 on 2023-06-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0024_imaginghistory_imagingupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imaginghistory',
            name='scantype',
            field=models.CharField(choices=[('MRI', 'MRI'), ('PET', 'PET')], max_length=100, null=True),
        ),
    ]
