# Generated by Django 4.2.1 on 2023-06-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0025_imaginghistory_scantype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imaginghistory',
            name='scantype',
        ),
        migrations.RemoveField(
            model_name='imaginghistory',
            name='visitEntry',
        ),
        migrations.AddField(
            model_name='imaginghistory',
            name='scanType',
            field=models.CharField(choices=[('MRI', 'MRI'), ('PET', 'PET')], default='MRI', max_length=100),
        ),
    ]
