# Generated by Django 4.2.1 on 2023-06-13 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0026_remove_imaginghistory_scantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imaginghistory',
            name='scanType',
            field=models.CharField(choices=[('MRI', 'MRI'), ('PET', 'PET'), ('X-Ray', 'X-Ray'), ('ECG', 'ECG'), ('CT', 'CT'), ('Ultrasound', 'Ultrasound'), ('Medical Photography', 'Medical Photography')], default='MRI', max_length=100),
        ),
        # migrations.AlterField(
        #     model_name='imagingupload',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
