# Generated by Django 4.2.1 on 2023-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0027_alter_imaginghistory_scantype_alter_imagingupload_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
