# Generated by Django 4.2.1 on 2023-06-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0025_medication_bypatient'),
        ('patientoncall_api', '0028_alter_imagingupload_id'),
    ]

    operations = [
    ]
