# Generated by Django 4.2.1 on 2023-06-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0025_diary_readbydoctor'),
        ('patientoncall_api', '0029_merge_20230614_0239'),
    ]

    operations = [
    ]
