# Generated by Django 4.2.1 on 2023-06-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0030_merge_20230614_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ('-startDate',)},
        ),
    ]
