# Generated by Django 4.2.1 on 2023-06-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patientoncall_api', '0031_alter_medication_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='patient',
        ),
        migrations.CreateModel(
            name='DiaryClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contentType', models.CharField(max_length=64)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='diaryClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientoncall_api.diaryclass'),
        ),
    ]
