# Generated by Django 4.2.1 on 2023-06-15 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0032_alter_medicalhistory_visittype'),
        ('patientoncall_api', '0032_remove_diary_patient_diaryclass_diary_diaryclass'),
    ]

    operations = [
    ]
