# Generated by Django 4.2.1 on 2023-06-15 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0034_labhistory_labtype_alter_labhistory_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labhistory',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
