# Generated by Django 4.2.1 on 2023-06-16 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0035_alter_labhistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imaginghistory',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='labhistory',
            options={'ordering': ('-date',)},
        ),
    ]
