# Generated by Django 4.2.1 on 2023-06-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientoncall_api', '0036_alter_imaginghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labhistory',
            name='visitEntry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientoncall_api.medicalhistory'),
        ),
    ]
